# Generated by Django 4.1.7 on 2023-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="my_store_app/static/"),
        ),
    ]
