# Generated by Django 4.1.7 on 2023-04-22 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0006_alter_payment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=256, verbose_name='Website url')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='номер  необходимо вводить в формате: 999999999 до 8 символов.', regex='^\\+?1?\\d{6,8}$')], verbose_name='номер счета'),
        ),
    ]
