# Generated by Django 4.1.7 on 2023-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0007_sitesettings_alter_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='free delivery'),
        ),
    ]
